### PR TITLE
Operator-SDK v1.25.0

### PR DESCRIPTION
**Pull request by mjlshen**
For OSD-13654, we want to enable Go 1.19 for rhobs.monitoring CRs, but first we had to update boilerplate in https://github.com/openshift/boilerplate/pull/246. This PR is a final validation that boilerplate is ready. I needed to do:

* `make boilerplate-update`
* Go 1.19
* Dependency bumps as indicated in https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.25.0

### CODE REVIEW

**Comment by mjlshen** [comment]
Depends on https://github.com/openshift/release/pull/33954

**Comment by 2uasimojo** [comment]
bp update is clean ✓

**Pull request merged**
