### PR TITLE
Update OLM template for hypershift deployments

### PR DESCRIPTION
**Pull request by sam-nguyen7**
Update OLM template to deploy AVO on:
- Hypershift management clusters
- Hypershift service clusters

- [x] TODO: find out if service clusters are non-STS
          Service & mgmt clusters are non-STS, so we can rely on CredentialsRequest!

### CODE REVIEW

**Comment by mjlshen** [comment]
/hold
/lgtm

Just holding due to your comment about checking if service/management clusters are STS or not. Feel free to remove the hold when ready.

**Comment by patjlm** [comment]
I don't understand why you'd want to use a single template for both fedramp and hypershift. Those 2 SSS would get deployed on both kind of environment, which is probably not the intent. I would recommend creating and other template. Alternatively, it might be possible to templatize the label selector somehow ?

**Pull request merged**
