### PR TITLE
boilerplate-update

### PR DESCRIPTION
**Pull request by mjlshen**
Keeping up to date with boilerplate as a result of the changes in [OSD-13790](https://issues.redhat.com//browse/OSD-13790)

### CODE REVIEW

**Comment by mjlshen** [comment]
Depends on https://github.com/openshift/release/pull/34127

**Comment by tonytheleg** [comment]
Per @mjlshen changes have been validated and tested in commercial, changes should not impact the functionality of the operator

/lgtm

**Pull request merged**
